apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: {{ .Values.service.port }}
    type: HTTP
    requestPath: /auth