apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-ui-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 3001
    type: HTTP
    requestPath: /