{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ui.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: itvsdp-context
          servicePort: 3000
        path: /ui/**
        pathType: ImplementationSpecific
      - backend:
          serviceName: itvsdp-keycloak-headless
          servicePort: 80
        path: /auth
        pathType: Prefix
      - backend:
          serviceName: itvsdp-bff-context
          servicePort: 8000
        path: /bff/**
        pathType: ImplementationSpecific
      - backend:
          serviceName: itvsdp-service-context
          servicePort: 8080
        path: /service/**
        pathType: ImplementationSpecific      
  {{- end }}
