apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ui.name" . }}
    helm.sh/chart: {{ include "ui.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    cloud.google.com/neg: '{"ingress": true,"exposed_ports":{"{{ .Values.service.port }}":{}}}'
    beta.cloud.google.com/backend-config: '{"default": "{{ include "ui.fullname" . }}-backend-config"}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3001              #{{ .Values.service.port }}  # 3001, dynamic from values.yaml
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}